### ISSUE TITLE
Neina passint neigiamų koordinačių kaip argumentų

### ISSUE THREAD

**Issue by rKsanu2MMYvypWePtQWM** [Woyken/pixelplanet.fun-bot#1]
Bandžiau tiesiog (kaip pvz) 123 -123, x randa be problemų, y nemato. Tas pats ir su "123" "-123". Rašant viską ranka kai paklausia veikia be problemų.

**Comment by Woyken** [comment]
Problemą žinau, nežinau kaip išspręsti...
NPM kažkodėl suvalgo parametrus su "-" priekyje.
Workaround:
"npx node ./dist/client.js -1555 -8545 mario.png"
Šitas veikia normaliai su visais parametrais

**Comment by rKsanu2MMYvypWePtQWM** [comment]
Ačiū! Linkiu rast sprendimą.
