### ISSUE TITLE
help

### ISSUE THREAD

**Issue by DablyaOfficial** [Woyken/pixelplanet.fun-bot#12]
https://i.imgur.com/g711s7k.jpg
Ubuntu 16.04

**Comment by Woyken** [comment]
Seems like issue on your machine.
My guess would be that your "tsc" file doesn't have executable permissions. Somehow by default it won't let execute it... Not sure how this would happen.
Most likely this is the file: "node_modules/typescript/bin/tsc"
Something like: "chmod +x ./node_modules/typescript/bin/tsc" might help.

**Comment by DablyaOfficial** [comment]
Unfortunately, the problem is not solved :(

**Comment by Woyken** [comment]
Well. I'm not sure how to help you. Anyway, seems like bots are no longer an option, because captcha was added. RIP
