### ISSUE TITLE
bot gives an error

### ISSUE THREAD

**Issue by Anitiger** [Woyken/pixelplanet.fun-bot#14]
Hello, the bot gives errors and nothing happens when there is a fix?
![Снимок экрана (274)](https://user-images.githubusercontent.com/51008923/58361588-3c841880-7ed3-11e9-86c1-d9e26328bc86.png)

**Comment by Woyken** [comment]
"Captcha was requested. Bot won't work anymore. Nothing to do about it, open up the site and play as regular person :(."

I thought this was clear enough. They added captchas to the page, those can't be solved automatically.

**Comment by Anitiger** [comment]
> «Требуется капча. Бот больше не будет работать. Ничего не поделаешь, откройте сайт и играйте как обычный человек :(.»
> 
> Я думал, что это было достаточно ясно. Они добавили капчи на страницу, они не могут быть решены автоматически.
so there will be no fix?

**Comment by Woyken** [comment]
There's nothing I can do at this point. As long as Captchas are enabled bots won't work

**Comment by Woyken** [comment]
Added option to solve captha manually.
