### ISSUE TITLE
Why code can't start?

### ISSUE THREAD

**Issue by goutosama** [Woyken/pixelplanet.fun-bot#16]
C:\Users\Сергей\Documents\pixelplanet.fun-bot-master>npm start -- -14351 -29087
fond.png 9a7004d88357826f8f1c7aa9d21857a6 n y none

> pixelplanet.fun-bot@1.0.14 start C:\Users\Сергей\Documents\pixelplanet.fun-bot
-master
> npm install && npm run build && npm run start-script -- "-14351" "-29087" "fon
d.png" "9a7004d88357826f8f1c7aa9d21857a6" "n" "y" "none"

npm WARN pixelplanet.fun-bot@1.0.14 No repository field.

audited 207 packages in 1.613s
found 2 vulnerabilities (1 low, 1 moderate)
  run `npm audit fix` to fix them, or `npm audit` for details

> pixelplanet.fun-bot@1.0.14 build C:\Users\Сергей\Documents\pixelplanet.fun-bot
-master
> tsc

> pixelplanet.fun-bot@1.0.14 start-script C:\Users\Сергей\Documents\pixelplanet.
fun-bot-master
> node ./dist/client.js "-14351" "-29087" "fond.png" "9a7004d88357826f8f1c7aa9d2
1857a6" "n" "y" "none"

Checking for updates...
Already up to date
x=-14351
y=-29087
imgPath=fond.png
Dither the image=false
constantWatch=false
customEdgesMapImagePath=none
-------------------------------------------
Starting with parameters: {"constantWatch":false,"customEdgesMapImagePath":"none
","ditherTheImage":false,"doNotOverrideColors":[null],"imgPath":"fond.png","xLef
tMost":-14351,"yTopMost":-29087}
Reading the picture...
Done reading. 416 x 62
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open 'C:\Users\Сергей\Documents\pixelp
lanet.fun-bot-master\none'
Emitted 'error' event at:
    at lazyFs.open (internal/fs/streams.js:115:12)
    at FSReqWrap.args [as oncomplete] (fs.js:140:20)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pixelplanet.fun-bot@1.0.14 start-script: `node ./dist/client.js "-14351
" "-29087" "fond.png" "9a7004d88357826f8f1c7aa9d21857a6" "n" "y" "none"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pixelplanet.fun-bot@1.0.14 start-script script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Сергей\AppData\Roaming\npm-cache\_logs\2019-06-11T09_44_42
_840Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pixelplanet.fun-bot@1.0.14 start: `npm install && npm run build && npm
run start-script -- "-14351" "-29087" "fond.png" "9a7004d88357826f8f1c7aa9d21857
a6" "n" "y" "none"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pixelplanet.fun-bot@1.0.14 start script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Сергей\AppData\Roaming\npm-cache\_logs\2019-06-11T09_44_42
_929Z-debug.log

**Comment by Woyken** [comment]
Your source files are out of date. I forgot to increase version number. Now it should update itself
