### ISSUE TITLE
Help! I don't understand

### ISSUE THREAD

**Issue by JlekTop** [Woyken/pixelplanet.fun-bot#17]
I do everything that is written, but it turns out:
------------------------
 Microsoft Windows [Version 6.1.7601]
(c) Корпорация Майкрософт (Microsoft Corp.), 2009. Все права защищены.

C:\Users\User>cd C:\Users\User\Desktop\pp

C:\Users\User\Desktop\pp>npm start - 2000  -12000 C:\Users\User\Desktop\pp\brati
shkin.png f60c10d5a08f7212f53092e08ee35a05 y n none

 pixelplanet.fun-bot@1.0.15 start C:\Users\User\Desktop\pp
 npm install && npm run build && npm run start-script -- "-" "2000" "C:\Users\U
ser\Desktop\pp\bratishkin.png" "f60c10d5a08f7212f53092e08ee35a05" "y" "n" "none"

npm WARN pixelplanet.fun-bot@1.0.15 No repository field.

audited 207 packages in 2.601s
found 2 vulnerabilities (1 low, 1 moderate)
  run `npm audit fix` to fix them, or `npm audit` for details

pixelplanet.fun-bot@1.0.15 build C:\Users\User\Desktop\pp
tsc

 pixelplanet.fun-bot@1.0.15 start-script C:\Users\User\Desktop\pp
 node ./dist/client.js "-" "2000" "C:\Users\User\Desktop\pp\bratishkin.png" "f6
0c10d5a08f7212f53092e08ee35a05" "y" "n" "none"

Checking for updates...
Already up to date
x=NaN
y=2000
imgPath=C:\Users\User\Desktop\pp\bratishkin.png
fingerprint=f60c10d5a08f7212f53092e08ee35a05
Dither the image=true
constantWatch=false

Starting with parameters: {"constantWatch":false,"customEdgesMapImagePath":"","d
itherTheImage":true,"doNotOverrideColors":[null],"fingerprint":"f60c10d5a08f7212
f53092e08ee35a05","imgPath":"C:\\Users\\User\\Desktop\\pp\\bratishkin.png","xLef
tMost":null,"yTopMost":2000}
Reading the picture...
Done reading. 280 x 280
expectedOutput.png <- Contains the final expected image.
currentlyMaking.png <- Contains the current edges map we're working with.
Initializing...
Ok, let's go!
Error: Chunk gathering responded with Not Found
    at C:\Users\User\Desktop\pp\dist\chunkCache.js:245:31
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
Starting listening for changes via websocket
Error: Chunk gathering responded with Not Found
    at C:\Users\User\Desktop\pp\dist\chunkCache.js:245:31
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
Error: Chunk gathering responded with Not Found
    at C:\Users\User\Desktop\pp\dist\chunkCache.js:245:31
    at processTicksAndRejections (internal/process/task_queues.js:89:5)

**Comment by Woyken** [comment]
Your start parameters are wrong.
"npm start -- x y ..."
You missed the double dash part "--"

**Comment by JlekTop** [comment]
thank you!
