### ISSUE TITLE
Help me pls

### ISSUE THREAD

**Issue by Seiba2** [Woyken/pixelplanet.fun-bot#18]
> pixelplanet.fun-bot@1.0.15 start C:\Users\User\Pictures\pixelplanet.fun-bot-master
> npm install && npm run build && npm run start-script -- "23626" "-23422" "C:\Users\User\Downloads\333.png" "1cf07c7650019887436b8587b8d454f5" "n" "y" "none"
> pixelplanet.fun-bot@1.0.15 start-script C:\Users\User\Pictures\pixelplanet.fun-bot-master
> node ./dist/client.js "23626" "-23422" "C:\Users\User\Downloads\333.png" "1cf07c7650019887436b8587b8d454f5" "n" "y" "none"
Checking for updates...
Already up to date
x=23626
y=-23422
imgPath=C:\Users\User\Downloads\333.png
fingerprint=1cf07c7650019887436b8587b8d454f5

-----------------------------------------
Error!
Fingerprint is invalid. Make sure your start command is correct.

Program usage:
    npm start -- x y imgPath fingerprint [dither constantWatch customDrawPattern]

    Parameters:
    x - leftmost pixel of the pixture.
    y - topmost pixel of the picture.
    image - path to your image. Can be URL to image.
    fingerprint - your fingerprint.
    dither - "y/n" option to dither your image. Often used to compensate for lack of colors in new pallet.
    constantWatch - after finished painting, bot will continue to watch over the painting and defend against any attacks.
    customDrawPattern - path to image (same size as input image). Bot drawing will start from "whitest" color and end with "blackest".

**Comment by Woyken** [comment]
Ok, so it seems like the fingerprint doesn't necessarily match regular GUID rules.
