### ISSUE TITLE
Error Invalid fingerprint

### ISSUE THREAD

**Issue by Seiba2** [Woyken/pixelplanet.fun-bot#19]
Error!
Fingerprint is invalid. Make sure your start command is correct
Program usage:
npm start -- x y imgPath fingerprint [dither constantWatch customDrawPattern]

fingerprint take from the browser. after setting the pixel, what's wrong?

**Comment by Woyken** [comment]
Likely fixed in [8cbddc1](https://github.com/Woyken/pixelplanet.fun-bot/commit/8cbddc12a5d59e998ff5c2648bb1d3e84cf4c929)
