### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by JlekTop** [Woyken/pixelplanet.fun-bot#22]
What is the error and why does it appear?
-------
![Video 0375](https://user-images.githubusercontent.com/51123407/60172317-dc5ff980-9825-11e9-8691-ccd539602795.jpg) Everything worked fine yesterday.

**Comment by Woyken** [comment]
My guess would be server is being slow again. I'll take a look at this later today if I find time for that

**Comment by David-337** [comment]
![image](https://user-images.githubusercontent.com/5092916/60268205-8c9c3380-98f4-11e9-9abf-659476f67855.png)
could this be the problem?

**Comment by Woyken** [comment]
Thanks for the post @David-337 it made fixing this really easy :D
