### ISSUE TITLE
Colors are not fully updated - color "touched water" (sky blue) has old id

### ISSUE THREAD

**Issue by player-char** [Woyken/pixelplanet.fun-bot#23]
"Untouched water" is now recognized as wrong color and being pointlessly redrawn.
Should change "19" to "25" (new "touched water" id) in these lines:

https://github.com/Woyken/pixelplanet.fun-bot/blob/a0e489a493094dbbb2a077562932b53d6c4628f4/src/colorConverter.ts#L63

https://github.com/Woyken/pixelplanet.fun-bot/blob/a0e489a493094dbbb2a077562932b53d6c4628f4/src/colorConverter.ts#L79

**Comment by Woyken** [comment]
Thanks for reporting, I wouldn't have noticed this, since I'm not running any bots right now
