### ISSUE TITLE
A possible enhancement for the bot. Add audio alerts.

### ISSUE THREAD

**Issue by User259720** [Woyken/pixelplanet.fun-bot#26]
Hello, Woyken!﻿
I've been using Your bot for quite a while already, and I'd like to thank You for all the work You've done. However, I would like to ask You about adding one more feature.﻿
Since the captcha confirmnation is requested quite often now, you have to check the bot operability manually, which is not really convenient. It would have been really nice if You add a feature of playing a custom audiofile, placed in the bot's directory by user, every time the bot stops working, using the system's default audioplayer.﻿ It's OK, if You won't add it for some reason. Anyway, thanks one more time and sorry for (possibly) bad English.﻿

**Comment by Woyken** [comment]
Thanks for the feedback. Since I'm not really using the bot myself, I don't notice such things 😅. I think this would be a nice addition. 
I'll see what I can do about that one.

**Comment by Woyken** [comment]
And... After looking around for a bit there doesn't seem to be an easy way to play sounds in node.js app in cross-platform friendly way 😢

**Comment by User259720** [comment]
Actually, I've never ever woked with node.js😅, but... may be this may help?
https://thisdavej.com/node-js-playing-sounds-to-provide-notifications/

**Comment by User259720** [comment]
Or this method isn't suitable for cross-platform?

**Comment by Woyken** [comment]
For this to work you would have to install one of these players:

![image](https://user-images.githubusercontent.com/13166802/60650568-0c725280-9e4d-11e9-8b42-5dbdcf47d048.png)

I don't have any of them, and don't think many of people do... I was searching for some solution that wouldn't require to install some external player for sound to work.

**Comment by User259720** [comment]
Sounds quite logical.
https://github.com/Marak/play.js
I'm completely not sure that I understood everything correctly, but what about this?
