### ISSUE TITLE
Bot failure

### ISSUE THREAD

**Issue by User259720** [Woyken/pixelplanet.fun-bot#27]
Hello, Woyken!
I would like to report to you a new issue. The issue was noticed at least at two devices, so it is certainly not a hardware or network problem. As far as I understand, it is caused by the public chat feature, added by Pixelplanet developers. Sometimes, when anything is written in the chat, the bot fails. It seems to me that at a certain moment the bot catches up the chat data except for the pixel map data, which causes an error. I hope that fixing it won't be too troublesome.
Thanks beforehand.
[2019-10-07T08_46_37_239Z-debug.log](https://github.com/Woyken/pixelplanet.fun-bot/files/3696853/2019-10-07T08_46_37_239Z-debug.log)

**Comment by Woyken** [comment]
Thanks for reporting this.
Yup, this seems to be caused by new chat messages.
Will fix it soon.
