### ISSUE TITLE
Can't find "Fingerprint" in Network Activity

### ISSUE THREAD

**Issue by Vitsowdy** [Woyken/pixelplanet.fun-bot#28]
I can't find fingerprint in network activity. I use Chrome.
![Screenshot](https://user-images.githubusercontent.com/56477530/66712631-41753600-eda8-11e9-8e4f-1e19a32748e8.png)

**Comment by Woyken** [comment]
Yup, they changed it a bit. Value in cookie: __cfduid=*****************. Should be the one you need.
Although I'm not sure if bot will continue to work now, that the value is passed by a cookie.

**Comment by Vitsowdy** [comment]
Nope, don't want work :/
`

C:\Users\Пользователь\Desktop\pixelplanet.fun-bot-master>npm start -- 13900 -10900 M.png d072436afbe1ef7657f3d401411bd46071570951437 y n none

> pixelplanet.fun-bot@1.0.20 start C:\Users\Пользователь\Desktop\pixelplanet.fun-bot-master
> npm install && npm run build && npm run start-script -- "13900" "-10900" "M.png" "d072436afbe1ef7657f3d401411bd46071570951437" "y" "n" "none"

npm WARN pixelplanet.fun-bot@1.0.20 No repository field.

audited 207 packages in 0.973s
found 3 vulnerabilities (1 low, 2 high)
  run `npm audit fix` to fix them, or `npm audit` for details

> pixelplanet.fun-bot@1.0.20 build C:\Users\Пользователь\Desktop\pixelplanet.fun-bot-master
> tsc


> pixelplanet.fun-bot@1.0.20 start-script C:\Users\Пользователь\Desktop\pixelplanet.fun-bot-master
> node ./dist/client.js "13900" "-10900" "M.png" "d072436afbe1ef7657f3d401411bd46071570951437" "y" "n" "none"

Checking for updates...
Already up to date
x=13900
y=-10900
imgPath=M.png
fingerprint=d072436afbe1ef7657f3d401411bd46071570951437

-----------------------------------------
Error!
Fingerprint is invalid. Make sure your start command is correct.

`

**Comment by Woyken** [comment]
I'll take a look what can i do about it and post a fix or at least an update. (Will update readme, on steps how to get fingerprint)

**Comment by Vitsowdy** [comment]
Ok, thanks

**Comment by Vitsowdy** [comment]
Will wait that

**Comment by Woyken** [comment]
Fixed in [8cbddc1](https://github.com/Woyken/pixelplanet.fun-bot/commit/8cbddc12a5d59e998ff5c2648bb1d3e84cf4c929)

**Comment by Vitsowdy** [comment]
Thanks
