### ISSUE TITLE
Socket Error while working

### ISSUE THREAD

**Issue by Vitsowdy** [Woyken/pixelplanet.fun-bot#29]
I started bot after new fix, and now he works, but i have error and he don't draw:
`
Starting with parameters: {"constantWatch":false,"customEdgesMapImagePath":"","ditherTheImage":true,"doNotOverrideColors":[null],"fingerprint":"d072436afbe1ef7657f3d401411bd46071570951437","imgPath":"M.png","xLeftMost":13900,"yTopMost":-10900}
Reading the picture...
Done reading. 70 x 70
currentlyMaking.png <- Contains the current edges map we're working with.
expectedOutput.png <- Contains the final expected image.
Initializing...
Ok, let's go!
TypeError: Cannot read property 'status' of undefined
    at axios_1.default.catch (c:\Users\Пользователь\Desktop\pixelplanet.fun-bot-master\dist\chunkCache.js:236:40)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Socket encountered error, closing socket connect ETIMEDOUT 104.31.80.140:443
Socket was closed. Reconnecting...
Socket encountered error, closing socket connect ETIMEDOUT 104.31.80.140:443
Socket was closed. Reconnecting...
TypeError: Cannot read property 'status' of undefined
    at axios_1.default.catch (c:\Users\Пользователь\Desktop\pixelplanet.fun-bot-master\dist\chunkCache.js:236:40)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Socket encountered error, closing socket connect ETIMEDOUT 104.31.80.140:443
Socket was closed. Reconnecting...
TypeError: Cannot read property 'status' of undefined
    at axios_1.default.catch (c:\Users\Пользователь\Desktop\pixelplanet.fun-bot-master\dist\chunkCache.js:236:40)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Socket encountered error, closing socket connect ETIMEDOUT 104.31.80.140:443
Socket was closed. Reconnecting...
TypeError: Cannot read property 'status' of undefined
    at axios_1.default.catch (c:\Users\Пользователь\Desktop\pixelplanet.fun-bot-master\dist\chunkCache.js:236:40)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Socket encountered error, closing socket connect ETIMEDOUT 104.31.80.140:443
Socket was closed. Reconnecting...
TypeError: Cannot read property 'status' of undefined
    at axios_1.default.catch (c:\Users\Пользователь\Desktop\pixelplanet.fun-bot-master\dist\chunkCache.js:236:40)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Socket encountered error, closing socket connect ETIMEDOUT 104.31.80.140:443
Socket was closed. Reconnecting...
`
Maybe i need open firewall ports or something else?

**Comment by Vitsowdy** [comment]
I guess, that it's conflict with Cloudflare protection, but i can't really say.

**Comment by Woyken** [comment]
Hmm.. If you have some custom protection, it might be causing this, blocking requests from other apps other than browser or something along those lines. I'm not sure...

**Comment by Tails-Dev** [comment]
Like antivirus programm?

**Comment by Vitsowdy** [comment]
Lol, ok.
So, i'm live in Russia, and PixelPlanet blocked here, so i need use VPN.
I used VPN, but it just Chrome extension, so Windows Shell didn't worked anyway.
Now it's started work.
If you have same problem, install VPN client.

**Comment by Vitsowdy** [comment]
But now i'm have infinity captcha check :/
`
Starting listening for changes via websocket
Initialization complete
Capthca was requested. Go to your browser, place a pixel and complete the captcha.
Press any key to continue
Pixel updated received: 13900:-10898, color: 31
Capthca was requested. Go to your browser, place a pixel and complete the captcha.
Press any key to continue
Pixel updated received: 13901:-10896, color: 31
Capthca was requested. Go to your browser, place a pixel and complete the captcha.
Press any key to continue
Capthca was requested. Go to your browser, place a pixel and complete the captcha.
Press any key to continue
Capthca was requested. Go to your browser, place a pixel and complete the captcha.
Press any key to continue
Capthca was requested. Go to your browser, place a pixel and complete the captcha.
Press any key to continue
Pixel updated received: 13942:-10870, color: 31
Pixel updated received: 13943:-10872, color: 31
Pixel updated received: 13948:-10870, color: 31
Pixel updated received: 13944:-10866, color: 31
Capthca was requested. Go to your browser, place a pixel and complete the captcha.
Press any key to continue
Pixel updated received: 13945:-10869, color: 31
Pixel updated received: 13946:-10868, color: 31
Pixel updated received: 13944:-10868, color: 31
Pixel updated received: 13945:-10868, color: 31
Pixel updated received: 13945:-10867, color: 31
Capthca was requested. Go to your browser, place a pixel and complete the captcha.
Press any key to continue
`

**Comment by Woyken** [comment]
I bet it's not Russia who is blocking pixelplanet it's the other way round. Since there were massive "griefing attacks" from Russia a while ago. Did not know that that could be the case.

About this captcha thing, if you enabled global vpn client, disable one on your chrome. I bet it gives different ips then to your browser instance and the "bot client". Then it would not work

**Comment by Vitsowdy** [comment]
Ok, i try it.

**Comment by Vitsowdy** [comment]
Wow, started working, thanks.

About different IP's, you're right.

**Comment by Woyken** [comment]
Glad it helped. Have fun :D

**Comment by Vitsowdy** [comment]
Thanks :D
