### ISSUE TITLE
?

### ISSUE THREAD

**Issue by popka228** [Woyken/pixelplanet.fun-bot#3]
![Screenshot_7](https://user-images.githubusercontent.com/30111286/57200025-e89aa980-6f8e-11e9-8c2b-8fffa979b8df.png)
log
[2019-05-05T20_25_02_034Z-debug.log](https://github.com/Woyken/pixelplanet.fun-bot/files/3146001/2019-05-05T20_25_02_034Z-debug.log)

**Comment by Woyken** [comment]
1. Your image is way too large.
2. You ran out of ram (to even load the picture).
3. Something's up with your nodejs installation.

**Comment by popka228** [comment]
what is the maximum size a pic can have?

**Comment by Woyken** [comment]
I haven't tried anything larger than 2MB. 
I can't imagine how huge your drawing would have to be with such image size. I would take years to finish.

**Comment by popka228** [comment]
ok thanks a lot for your reply
