### ISSUE TITLE
Problem after update

### ISSUE THREAD

**Issue by xTMMDx** [Woyken/pixelplanet.fun-bot#4]
Nothing happens after this message. Please help
![1](https://user-images.githubusercontent.com/50329496/57239797-96609380-7035-11e9-9410-2bdd1f8bd814.PNG)
After a recent update
![1](https://user-images.githubusercontent.com/50329496/57242332-e93d4980-703b-11e9-93ce-211d6ebfdb86.PNG)

**Comment by Woyken** [comment]
I have no idea what happened the first time.
The second picture, my mistake, fixed now.

**Comment by xTMMDx** [comment]
> I have no idea what happened the first time.
> The second picture, my mistake, fixed now.
Now another error
![1](https://user-images.githubusercontent.com/50329496/57243136-01ae6380-703e-11e9-909b-0f97afc15c3e.PNG)

**Comment by Woyken** [comment]
![image](https://user-images.githubusercontent.com/13166802/57243212-37ebe300-703e-11e9-9acf-ff1ca4ebf0e1.png)
Your provided X coordinate is read as null

**Comment by xTMMDx** [comment]
> ![image](https://user-images.githubusercontent.com/13166802/57243212-37ebe300-703e-11e9-9acf-ff1ca4ebf0e1.png)
> Your provided X coordinate is read as null

No, it rewrites it into null.

**Comment by Woyken** [comment]
From the first picture I can see that you didn't start program properly. "... start -- xxx yyy ..." you missed the '--'

**Comment by xTMMDx** [comment]
Here is the command that worked today before the penultimate update: "npm start — 2508 -10404 tmd.png y y none". Now it doesn't work

**Comment by Woyken** [comment]
this couldn't work. The "—" is just 1 symbol, not "--"

**Comment by xTMMDx** [comment]
Oh, I'm always copy-pasted this into git, but I didn't know that "--" changes to "-" if I do not write the command manually. THANK!
