### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by xTMMDx** [Woyken/pixelplanet.fun-bot#6]
![Снимок](https://user-images.githubusercontent.com/50329496/57568941-ca053a00-73f6-11e9-9572-4b8487914701.PNG)

**Comment by Woyken** [comment]
Oh come on. This is their server error, ie., 5xx error. Their server can't handle all the requests from time to time.
![image](https://user-images.githubusercontent.com/13166802/57569004-fec5c100-73f7-11e9-926e-9f310894392b.png)
