### ISSUE TITLE
Lost Y

### ISSUE THREAD

**Issue by EgrorBs** [Woyken/pixelplanet.fun-bot#7]
![image](https://user-images.githubusercontent.com/44816767/57583077-859c9b80-74d5-11e9-94ea-3d0122a60849.png)

**Comment by Woyken** [comment]
![image](https://user-images.githubusercontent.com/13166802/57583122-ea57f600-74d5-11e9-95f6-7b8c570d431e.png)

**Comment by EgrorBs** [comment]
Okey, thank you.
