### ISSUE TITLE
stops working after update received

### ISSUE THREAD

**Issue by lolmaxlevel** [Woyken/pixelplanet.fun-bot#8]
![Screenshot_1](https://user-images.githubusercontent.com/50590135/57636699-4c862900-75b2-11e9-983e-2e39adb973a5.png)

**Comment by Woyken** [comment]
Your screenshot does not contain any error.

**Comment by lolmaxlevel** [comment]
This is not an error, the program just stops displaying anything in the console after update received

**Comment by lolmaxlevel** [comment]
I reinstalled and the problem it seems was gone
