### ISSUE TITLE
error 400 

### ISSUE THREAD

**Issue by yan0f** [Woyken/pixelplanet.fun-bot#9]
Error: Pixel posting responded with Request failed with status code 400

**Comment by Woyken** [comment]
I'm not getting that one.
After restart same happens? Every "placement" returns this error, or every once in a while?

**Comment by yan0f** [comment]
Yes. Every placement.

**Comment by Woyken** [comment]
Without screenshot, and more details, like parameters (printed when program starts) there's not much I can think of that might be the issue.

**Comment by yan0f** [comment]
`Yans-MacBook-Pro:pixelplanet.fun-bot-master yanf.$ npm start -- 25983 51000 png.png n y none

> pixelplanet.fun-bot@1.0.10 start /Users/yanf./Downloads/pixelplanet.fun-bot-master
> npm install && npm run build && npm run start-script -- "25983" "51000" "png.png" "n" "y" "none"

npm WARN pixelplanet.fun-bot@1.0.10 No repository field.

audited 207 packages in 2.632s
found 2 vulnerabilities (1 low, 1 moderate)
  run `npm audit fix` to fix them, or `npm audit` for details

> pixelplanet.fun-bot@1.0.10 build /Users/yanf./Downloads/pixelplanet.fun-bot-master
> tsc


> pixelplanet.fun-bot@1.0.10 start-script /Users/yanf./Downloads/pixelplanet.fun-bot-master
> node ./dist/client.js "25983" "51000" "png.png" "n" "y" "none"

Checking for updates...
Newer version found, updating...
Update complete. Restarting...

> pixelplanet.fun-bot@1.0.12 start /Users/yanf./Downloads/pixelplanet.fun-bot-master
> npm install && npm run build && npm run start-script -- "25983" "51000" "png.png" "n" "y" "none"

npm WARN pixelplanet.fun-bot@1.0.12 No repository field.

audited 207 packages in 1.466s
found 2 vulnerabilities (1 low, 1 moderate)
  run `npm audit fix` to fix them, or `npm audit` for details

> pixelplanet.fun-bot@1.0.12 build /Users/yanf./Downloads/pixelplanet.fun-bot-master
> tsc


> pixelplanet.fun-bot@1.0.12 start-script /Users/yanf./Downloads/pixelplanet.fun-bot-master
> node ./dist/client.js "25983" "51000" "png.png" "n" "y" "none"

Checking for updates...
Already up to date
x=25983
y=51000
imgPath=png.png
Dither the image=false
constantWatch=true
-------------------------------------------
Starting with parameters: {"constantWatch":true,"customEdgesMapImagePath":"","ditherTheImage":false,"doNotOverrideColors":[null],"imgPath":"png.png","xLeftMost":25983,"yTopMost":51000}
Reading the picture...
Done reading. 200 x 200
expectedOutput.png <- Contains the final expected image.
currentlyMaking.png <- Contains the current edges map we're working with.
Initializing...
Ok, let's go!
Starting listening for changes via websocket
Error: Pixel posting responded with Request failed with status code 400
    at /Users/yanf./Downloads/pixelplanet.fun-bot-master/dist/chunkCache.js:96:31
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
Error: Pixel posting responded with Request failed with status code 400
    at /Users/yanf./Downloads/pixelplanet.fun-bot-master/dist/chunkCache.js:96:31
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
Initialization complete
Error: Pixel posting responded with Request failed with status code 400
    at /Users/yanf./Downloads/pixelplanet.fun-bot-master/dist/chunkCache.js:96:31
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
Error: Pixel posting responded with Request failed with status code 400
    at /Users/yanf./Downloads/pixelplanet.fun-bot-master/dist/chunkCache.js:96:31
`

**Comment by Woyken** [comment]
Pushed an update. See if that helps. Should see in the log few more details on the failure (what color it's trying to place and exactly where).
